Device.LocalAgent.EndpointID "controller-1"

Device.LocalAgent.MTP.1.Alias "controller-mqtt"
Device.LocalAgent.MTP.1.Enable true
Device.LocalAgent.MTP.1.Protocol "MQTT"
Device.LocalAgent.MTP.1.MQTT.Reference "Device.MQTT.Client.1"
Device.LocalAgent.MTP.1.MQTT.ResponseTopicConfigured "/usp/endpoint/#"

Device.LocalAgent.Controller.1.Alias "local-agent"
Device.LocalAgent.Controller.1.Enable true
Device.LocalAgent.Controller.1.PeriodicNotifInterval "86400"
Device.LocalAgent.Controller.1.PeriodicNotifTime "0001-01-01T00:00:00Z"
Device.LocalAgent.Controller.1.ControllerCode ""
Device.LocalAgent.Controller.1.MTP.1.Alias "controller-mqtt"
Device.LocalAgent.Controller.1.MTP.1.Enable true
Device.LocalAgent.Controller.1.MTP.1.Protocol "MQTT"
Device.LocalAgent.Controller.1.EndpointID "os::14360E-S240Y41000039"
Device.LocalAgent.Controller.1.MTP.1.MQTT.Reference "Device.MQTT.Client.1"
Device.LocalAgent.Controller.1.MTP.1.MQTT.Topic "/usp/controller"

Device.MQTT.Client.1.Alias "controller-1"
Device.MQTT.Client.1.Enable true
Device.MQTT.Client.1.BrokerAddress "mqtt"
Device.MQTT.Client.1.ProtocolVersion "5.0"
Device.MQTT.Client.1.BrokerPort "8883"
Device.MQTT.Client.1.TransportProtocol "TLS"
Device.MQTT.Client.1.Username ""
Device.MQTT.Client.1.Password ""
Device.MQTT.Client.1.ClientID "controller-1"
Device.MQTT.Client.1.KeepAliveTime "60"
Device.MQTT.Client.1.ConnectRetryTime "5"
Device.MQTT.Client.1.ConnectRetryIntervalMultiplier "2000"
Device.MQTT.Client.1.ConnectRetryMaxInterval "60"