ControllerEndpointID = "lab-controller"

# MQTT transport
MqttEnable = true
MqttHost = mqtt
MqttPort = 1883

# WebSocket transport
WebSocketEnable = true
WebSocketPort = 9001

# TLS files
SslCertFile = /certs/server.crt
SslKeyFile  = /certs/server.key
SslCAFile   = /certs/ca.crt

LogLevel = debug